### ISSUE TITLE
Maps for the lab/kitchen

### ISSUE THREAD

**Issue by fairlight1337** [code-iai/longterm_fetch_and_place#1]
I heard that @gaya- and @gheorghelisca were making a floor map of the kitchen area in the lab that can be used for the demo. Can you supply that? And if not, can you make one that can be used? Thanks.

**Comment by gaya-** [comment]
The latest occupancy map is https://github.com/code-iai/iai_maps/blob/master/iai_maps/maps/map-2016-06-17.pgm
Creating a new map takes half an hour to set things up and record data and maybe another half an hour to edit the file in Gimp if we want to keep the original rotation.
Are we done with moving the stuff in the lab around?
If we are and no one else want to do the new map, let me know and I'll do it quickly.

**Comment by fairlight1337** [comment]
No, it's not done yet. Alexis said he could move back the walls. No idea when he planned to do that.

**Comment by fairlight1337** [comment]
This was done to a sufficient degree.
