### ISSUE TITLE
Navigation failing due to actionlib timeout

### ISSUE THREAD

**Issue by fairlight1337** [code-iai/longterm_fetch_and_place#11]
While the robot is still moving, the navigation call gets cancelled and preempted. This happens due to a timeout in actionlib (according to the console output):

```
[(PR2-NAV PROCESS-MODULE) INFO] 13336.711: Using nav-pcontroller.
[(ACTIONLIB) INFO] 13345.474: Reached execute timeout.
[(PR2-NAV PROCESS-MODULE) INFO] 13345.476: Nav action finished.
[(PR2-NAV PROCESS-MODULE) WARN] 13345.476: Goal not reached. Linear distance: 0.2698605719169658d0, angular distance: 6.003684350544216d0
[(PR2-NAV PROCESS-MODULE) INFO] 13345.476: Navigation finished.
```

This throws a failure of type `CRAM-PLAN-FAILURES:LOCATION-NOT-REACHED-FAILURE` and the robot is somewhere between its initial and its goal pose. This only happens every once in a while when the robot needs to drive sufficiently far (like 2 meters or so).

This is probably resolved setting a higher actionlib timeout, but

``` lisp
(setf actionlib::*action-server-timeout* 20)
```

didn't fix it. This is then probably related to `actionlib` vs. `actionlib-lisp`, but I'll have to look into that.

**Comment by gaya-** [comment]
https://github.com/cram2/cram_pr2/blob/master/pr2_navigation_process_module/src/process-module.lisp#L119

**Comment by fairlight1337** [comment]
Ah! Fixed timeouts :). That explains that, thanks. And it was even me who set them (according to `git blame`). I'll take them out; the global or default timeouts should be used, anyway. Or do you see any trouble related to that?

**Comment by fairlight1337** [comment]
Closed by https://github.com/cram2/cram_pr2/commit/4f4c1d969bd88bd08c1608d65699bea43334165d.
