### ISSUE TITLE
Making CRAM demos great again

### ISSUE THREAD

**Issue by fairlight1337** [code-iai/longterm_fetch_and_place#2]
Hey @gaya-, can you try out the current state of the demo package (Gazebo, load the CRAM package, start the launch file `ltfnp_simulation.launch` in `ltfnp_executive`)? We should verify every now and then that this runs on multiple systems and has viable dependencies. Thanks.

**Comment by gaya-** [comment]
I tested it. The launch files and the compilation works. Compilation in Lisp gives a lot of warnings but it also works for me.

**Comment by airballking** [comment]
Interesting title.

**Comment by fairlight1337** [comment]
Subconscious media influence.

**Comment by fairlight1337** [comment]
@gaya- Great! Thanks for testing. Glad it works in its current state. I'll put up a list of things that need finishing; if anything comes to your mind, please add it there.

**Comment by fairlight1337** [comment]
The issue is [here](https://github.com/code-iai/longterm_fetch_and_place/issues/4)
